dist: trusty
sudo: required
language: 
- node_js

node_js:
- '10'

install:
- npm i -g npm
- npm i -g browsertime 
- npm i -g http-server 

cache:
  directories:
  - node_modules

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable fluxbox

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- fluxbox >/dev/null 2>&1 &
- http-server >/dev/null 2>&1 &

script:
- browsertime logTest.js
